version: '3'

services:
  nginx:
   image: nginx:stable-alpine
   container_name: nginx
   command: [nginx-debug, '-g', 'daemon off;']
   restart: always
   ports:
     - 80:80
     - 443:443
   environment:
     TZ: 'Asia/Shanghai'
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./www:/etc/nginx/www
     - ./conf.d:/etc/nginx/conf.d
     - ./cert/letsencrypt:/etc/letsencrypt
     - /var/log/filebeat/nginx/:/var/log/nginx/
   logging:
     driver: "json-file"
     options:
       max-size: "200k"
       max-file: "10"

