version: '3'

networks:
  elastic:
    driver: bridge

services:
  elasticsearch-ui-elasticHD:
    image: containerize/elastichd
    container_name: elasticsearch-ui-elasticHD
    ports:
      - 9800:9800
    networks:
      - elastic