# https://www.docker.elastic.co
version: '3'

networks:
  elastic:
    driver: bridge

services:
  kibana01:
    image: kibana:7.14.1
    container_name: kibana01
    ports:
      - 5601:5601
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_NAME: kibana01
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: '["http://elastic:changme@elasticsearch01:9200","http://elastic:changme@elasticsearch02:9200","http://elastic:changme@elasticsearch03:9200"]'
      #ELASTICSEARCH_USERNAME: elastic
      #ELASTICSEARCH_PASSWORD: changme
      I18N_LOCALE: zh-CN
      # SERVER_SSL_ENABLED: "true"
      # SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      # SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt

  kibana02:
    image: kibana:7.14.1
    container_name: kibana02
    ports:
      - 5602:5601
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_NAME: kibana02
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: '["http://elastic:changme@elasticsearch01:9200","http://elastic:changme@elasticsearch02:9200","http://elastic:changme@elasticsearch03:9200"]'
      #ELASTICSEARCH_USERNAME: elastic
      #ELASTICSEARCH_PASSWORD: changme
      I18N_LOCALE: zh-CN
      # SERVER_SSL_ENABLED: "true"
      # SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      # SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt