# https://www.docker.elastic.co
version: '3'

networks:
  elastic:
    driver: bridge

services:
  kibana.node01:
    image: kibana:7.14.1
    container_name: kibana.node01
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./elasticsearch.certs:/usr/share/kibana/config/certificates
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_NAME: kibana.node01
      SERVER_HOST: 0.0.0.0
      SERVER_PUBLICBASEURL: http://0.0.0.0:5601
      ELASTICSEARCH_URL: https://elasticsearch.node01:9200
      ELASTICSEARCH_HOSTS: '["https://elasticsearch.node01:9200","https://elasticsearch.node02:9201","https://elasticsearch.node03:9202"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: AWEny6psWSuWZ0auwNGC
      I18N_LOCALE: zh-CN
      SERVER_SSL_ENABLED: "true"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/kibana/config/certificates/ca/ca.crt
      SERVER_SSL_KEY: /usr/share/kibana/config/certificates/kibana.node01/kibana.node01.key
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/certificates/kibana.node01/kibana.node01.crt
      XPACK_SECURITY_SESSION_IDLETIMEOUT: "10m"
      XPACK_SECURITY_SESSION_LIFESPAN: "10m"
      XPACK_SECURITY_ENCRYPTIONKEY: "bbfe8ae38274521f9311cb5467cbee41"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "abf6f2da5ba45222b4e66e38d50e7d63"

  kibana.node02:
    image: kibana:7.14.1
    container_name: kibana.node02
    ports:
      - 5602:5601
    networks:
      - elastic
    volumes:
      - ./elasticsearch.certs:/usr/share/kibana/config/certificates
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_NAME: kibana.node02
      SERVER_HOST: 0.0.0.0
      SERVER_PUBLICBASEURL: http://0.0.0.0:5601
      ELASTICSEARCH_URL: https://elasticsearch.node01:9200
      ELASTICSEARCH_HOSTS: '["https://elasticsearch.node01:9200","https://elasticsearch.node02:9201","https://elasticsearch.node03:9202"]'
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "AWEny6psWSuWZ0auwNGC"
      I18N_LOCALE: zh-CN
      SERVER_SSL_ENABLED: "true"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/kibana/config/certificates/ca/ca.crt
      SERVER_SSL_KEY: /usr/share/kibana/config/certificates/kibana.node02/kibana.node02.key
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/certificates/kibana.node02/kibana.node02.crt
      XPACK_SECURITY_SESSION_IDLETIMEOUT: "10m"
      XPACK_SECURITY_SESSION_LIFESPAN: "10m"
      XPACK_SECURITY_ENCRYPTIONKEY: "bbfe8ae38274521f9311cb5467cbee41"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "abf6f2da5ba45222b4e66e38d50e7d63"