# https://github.com/sheepkiller/kafka-manager-docker
version: '3'

networks:
  fixednet:
    external:
      name: zookeeper_fixednet

services:
  kafka-ui-manager:
    image: sheepkiller/kafka-manager
    restart: always
    hostname: kafka-ui-manager
    container_name: kafka-ui-manager
    ports:
      - 9000:9000
    environment:
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
      ZK_HOSTS: zookeeper.01:2181,zookeeper.02:2182,zookeeper.03:2183
    networks:
      - fixednet