# https://registry.hub.docker.com/_/influxdb
version: '3'

services:
  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - ./data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
































