# https://registry.hub.docker.com/_/influxdb
version: '3'

networks:
  influxdb:
    driver: bridge

volumes:
  influxdb1:
    driver: local
  influxdb2:
    driver: local

services:
  influxdb1:
    image: influxdb:1.8
    container_name: influxdb1
    restart: always
    networks:
      - influxdb
    ports:
      - 8086:8086
      - 2003:2003
    volumes:
      - ./influxdb1:/var/lib/influxdb
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=db0
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root

  influxdb2:
    image: influxdb:2.0
    container_name: influxdb2
    restart: always
    networks:
      - influxdb
    ports:
      - 9999:9999
      - 8086:8086
      - 2003:2003
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=db0
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket0
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xxxxxxxxxxxxxxxx
































