# https://gogs.io/
version: '3'

services:
  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    ports:
      - "13000:3000"
      - "10022:22"
    volumes:
      - ./data:/data