version: '3'

networks:
  redis:
    driver: bridge

volumes:
  redis-master:
    driver: local
  redis-slave1:
    driver: local
  redis-slave2:
    driver: local

services:
  redis-master:
    image: redis
    container_name: redis-master
    command: redis-server
      --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - redis-master:/data
      #- ./redis-master:/usr/local/etc/redis
    networks:
      - redis

  redis-slave1:
    image: redis
    container_name: redis-slave1
    command: redis-server
      --slaveof redis-master 6379
      --masterauth 123456
      --requirepass 123456
    ports:
      - 6380:6379
    volumes:
      - redis-slave1:/data
      #- ./redis-slave1:/usr/local/etc/redis
    networks:
      - redis

  redis-slave2:
    image: redis
    container_name: redis-slave2
    command: redis-server
      --slaveof redis-master 6379
      --masterauth 123456
      --requirepass 123456
    ports:
      - 6381:6379
    volumes:
      - redis-slave2:/data
      #- ./redis-slave2:/usr/local/etc/redis
    networks:
      - redis