version: '3'

networks:
  redis:
    driver: bridge

services:
  redis-sentinel1:
    image: redis
    container_name: redis-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    volumes:
      - ./redis-sentinel1:/usr/local/etc/redis
    networks:
      - redis

  redis-sentinel2:
    image: redis
    container_name: redis-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26380:26379
    volumes:
      - ./redis-sentinel2:/usr/local/etc/redis
    networks:
      - redis

  redis-sentinel3:
    image: redis
    container_name: redis-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26381:26379
    volumes:
      - ./redis-sentinel3:/usr/local/etc/redis
    networks:
      - redis
